<a href="https://colab.research.google.com/github/ia234/Python_23/blob/main/Python_Cheat_Sheet_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python

## Data Types

Numeric Data Types:

In [ ]:
# integer
my_int = 10
print(type(my_int))  # Output: <class 'int'>

# floating-point number
my_float = 3.14
print(type(my_float))  # Output: <class 'float'>

# complex number
my_complex = 2 + 3j
print(type(my_complex))  # Output: <class 'complex'>


<class 'int'>
<class 'float'>
<class 'complex'>


Sequence Data Types:

In [ ]:
# string
my_string = "Hello, World!"
print(type(my_string))  # Output: <class 'str'>

# list This is a collection of items that are ordered and changeable.
my_list = [1, 2, "three", True]
print(type(my_list))  # Output: <class 'list'>

# tuple This is a collection of items that are ordered and unchangeable.
my_tuple = (1, 2, "three", True)
print(type(my_tuple))  # Output: <class 'tuple'>

# range The range function is used to create a sequence of numbers, and it returns a range object. 
my_range = range(5)
print(type(my_range))  # Output: <class 'range'>



<class 'str'>
<class 'list'>
<class 'tuple'>
<class 'range'>


Mapping Data Type:

In [ ]:
# dictionary: This is a collection of key-value pairs that are unordered and changeable.
my_dict = {"name": "John", "age": 30, "city": "New York"}
print(type(my_dict))  # Output: <class 'dict'>


<class 'dict'>


Set Data Type:

In [ ]:
# set: This is a collection of unique items that are unordered and unindexed.
my_set = {1, 2, "three", True}
print(type(my_set))  # Output: <class 'set'>


# frozenset The frozenset function is used to create an immutable set, and it returns a frozenset object.
my_frozenset = frozenset({1, 2, 3})
print(type(my_frozenset))  # Output: <class 'frozenset'>


<class 'set'>
<class 'frozenset'>


**Boolean Data Type:**

In [ ]:
# boolean: This is a data type that represents True or False values.
my_bool = True
print(type(my_bool))  # Output: <class 'bool'>


<class 'bool'>


## Arithmetic Operators

In [ ]:
x = 9
y = 7

# Addition
z = x + y  # add x and y
print(z)

# Subtraction
z = x - y  # subtract y from x
print(z)

# Multiplication
z = x * y  # multiply x and y
print(z)

# Division
z = x / y  # divide x by y
print(z)

# Floor Division
z = x // y  # divide x by y and round down to the nearest integer
print(z)

# Modulus
z = x % y  # find the remainder of x divided by y
print(z)

# Exponentiation
z = x ** y  # raise x to the power of y
print(z)


16
2
63
1.2857142857142858
1
2
4782969


## Lists

### List Subsetting & Slicing

In [ ]:
# Define a list of fruits
fruits = ["apple", "banana", "cherry", "date", "elderberry"]

# Access a single element using its index (starts at 0)
print(fruits[0])    # Output: "apple"
print(fruits[2])    # Output: "cherry"

# Access a range of elements using a slice
print(fruits[1:4])  # Output: ["banana", "cherry", "date"]
print(fruits[:3])   # Output: ["apple", "banana", "cherry"]
print(fruits[3:])   # Output: ["date", "elderberry"]

# Access elements from the end of the list using negative indexing
print(fruits[-1])   # Output: "elderberry"
print(fruits[-3:])  # Output: ["cherry", "date", "elderberry"]




apple
cherry
['banana', 'cherry', 'date']
['apple', 'banana', 'cherry']
['date', 'elderberry']
elderberry
['cherry', 'date', 'elderberry']


### List operations and Functions

In [ ]:
# Check if Item Exists
if "apple" in fruits:
    print("Yes, 'apple' is in the fruits list")  # Output: "Yes, 'apple' is in the fruits list"

# Access List Items
for fruit in fruits:
    print(fruit)  # Output: "apple", "banana", "cherry"

# Change List Items
fruits[1] = "kiwi"
print(fruits)  # Output: ["apple", "kiwi", "cherry"]

# Add List Items
fruits.append("orange")
print(fruits)  # Output: ["apple", "kiwi", "cherry", "orange"]

# Remove List Items
fruits.remove("kiwi")
print(fruits)  # Output: ["apple", "cherry", "orange"]

# Loop Lists
for fruit in fruits:
    print(fruit)  # Output: "apple", "cherry", "orange"

# List Comprehension
new_list = [fruit for fruit in fruits if "a" in fruit]
print(new_list)  # Output: ["apple", "orange"]

# Sort Lists
fruits.sort()
print(fruits)  # Output: ["apple", "cherry", "orange"]

# Copy Lists in 3 ways:
# 1. using .copy() method
new_fruits = fruits.copy()
print(new_fruits)  # Output: ["apple", "cherry", "orange"]

# 2. using the list() function
# list_x = list(y) 

# 3. using the slicing operator 
# list_x = list_y[:]

# list_x = list_y copies the pointer to that list which causes any changes to list x to take effect in list y too.


# Join Lists
vegetables = ["beetroot", "carrot", "spinach"]
food = fruits + vegetables
print(food)  # Output: ["apple", "cherry", "orange", "beetroot", "carrot", "spinach"]


Yes, 'apple' is in the fruits list
apple
banana
cherry
date
elderberry
['apple', 'kiwi', 'cherry', 'date', 'elderberry']
['apple', 'kiwi', 'cherry', 'date', 'elderberry', 'orange']
['apple', 'cherry', 'date', 'elderberry', 'orange']
apple
cherry
date
elderberry
orange
['apple', 'date', 'orange']
['apple', 'cherry', 'date', 'elderberry', 'orange']
['apple', 'cherry', 'date', 'elderberry', 'orange']
['apple', 'cherry', 'date', 'elderberry', 'orange', 'beetroot', 'carrot', 'spinach']


### List Methods

Here are 25 of the most frequently used list methods in Python, ranked in order from most frequently used to least frequently used:

1. `append()` - Adds an element to the end of a list.
2. `len()` - Returns the length of a list.
3. `index()` - Returns the index of the first element with the specified value.
4. `count()` - Returns the number of elements with the specified value.
5. `pop()` - Removes the element at the specified position from a list, and returns it.
6. `sort()` - Sorts the elements of a list in ascending order.
7. `reverse()` - Reverses the order of the elements in a list.
8. `extend()` - Adds the elements of another list to the end of a list.
9. `insert()` - Adds an element at the specified position in a list.
10. `remove()` - Removes the first occurrence of a specified element from a list.
11. `copy()` - Returns a shallow copy of a list.
12. `clear()` - Removes all the elements from a list.
13. `max()` - Returns the largest element in a list.
14. `min()` - Returns the smallest element in a list.
15. `sum()` - Returns the sum of all elements in a list.
16. `join()` - Joins the elements of a list into a string.
17. `split()` - Splits a string into a list.
18. 
19. `index()` - Returns the index of the first occurrence of a specified element in a list.
20. `isinstance()` - Returns True if a variable is a list.
21. `enumerate()` - Returns an enumerate object.
22. `map()` - Applies a function to every element of a list.
23. `filter()` - Filters the elements of a list based on a function.
24. `zip()` - Combines two or more lists into a single list of tuples.
25. `any()` - Returns True if any element of a list is True.

In [ ]:
# Here are the 25 most frequently used list methods in Python, ranked in order from most frequently used to least frequently used, with comments and examples:

# 1. append() - Adds an element to the end of a list.
fruits = ["apple", "banana", "cherry"]
fruits.append("orange")
print(fruits) # Output: ["apple", "banana", "cherry", "orange"]

# 2. len() - Returns the length of a list.
fruits = ["apple", "banana", "cherry"]
print(len(fruits)) # Output: 3

# 3. index() - Returns the index of the first element with the specified value.
fruits = ["apple", "banana", "cherry"]
print(fruits.index("cherry")) # Output: 2

# 4. count() - Returns the number of elements with the specified value.
fruits = ["apple", "banana", "cherry", "cherry"]
print(fruits.count("cherry")) # Output: 2

# 5. pop() - Removes the element at the specified position from a list, and returns it.
fruits = ["apple", "banana", "cherry"]
fruits.pop(1)
print(fruits) # Output: ["apple", "cherry"]

# 6. sort() - Sorts the elements of a list in ascending order.
fruits = ["banana", "cherry", "apple"]
fruits.sort()
print(fruits) # Output: ["apple", "banana", "cherry"]

# 7. reverse() - Reverses the order of the elements in a list.
fruits = ["apple", "banana", "cherry"]
fruits.reverse()
print(fruits) # Output: ["cherry", "banana", "apple"]

# 8. extend() - Adds the elements of another list to the end of a list.
fruits = ["apple", "banana", "cherry"]
cars = ["Ford", "BMW", "Volvo"]
fruits.extend(cars)
print(fruits) # Output: ["apple", "banana", "cherry", "Ford", "BMW", "Volvo"]

# 9. insert() - Adds an element at the specified position in a list.
fruits = ["apple", "banana", "cherry"]
fruits.insert(1, "orange")
print(fruits) # Output: ["apple", "orange", "banana", "cherry"]

# 10. remove() - Removes the first occurrence of a specified element from a list.
fruits = ["apple", "banana", "cherry"]
fruits.remove("banana")
print(fruits) # Output: ["apple", "cherry"]

# 11. copy() - Returns a shallow copy of a list.
fruits = ["apple", "banana", "cherry"]
fruits_copy = fruits.copy()
print(fruits_copy) # Output: ["apple", "banana", "cherry"]

# 12. clear() - Removes all the elements from a list.
fruits = ["apple", "banana", "cherry"]
fruits.clear()
print(fruits) # Output: []

# 13. max() - Returns the largest element in a list.
numbers = [1, 2, 3, 4, 5]
print(max(numbers)) # Output: 5

# 14. min() - Returns the smallest element in a list.
numbers = [1, 2, 3, 4, 5]
print(min(numbers)) # Output: 1

# 1. sum() - Returns the sum of all elements in a list.
numbers = [1, 2, 3, 4, 5]
result = sum(numbers)
print(result)  # Output: 15

# 2. join() - Joins the elements of a list into a string.
words = ["Hello", "world", "!"]
result = " ".join(words)
print(result)  # Output: "Hello world !"

# 3. split() - Splits a string into a list.
sentence = "Hello world !"
words = sentence.split()
print(words)  # Output: ["Hello", "world", "!"]

# 4. 

# 5. index() - Returns the index of the first occurrence of a specified element in a list.
fruits = ["apple", "banana", "cherry"]
index = fruits.index("banana")
print(index)  # Output: 1

# 6. isinstance() - Returns True if a variable is a list.
fruits = ["apple", "banana", "cherry"]
result = isinstance(fruits, list)
print(result)  # Output: True

# 7. enumerate() - Returns an enumerate object.
fruits = ["apple", "banana", "cherry"]
for index, value in enumerate(fruits):
    print(index, value)  # Output: 0 apple, 1 banana, 2 cherry

# 8. map() - Applies a function to every element of a list.
numbers = [1, 2, 3, 4, 5]
squares = list(map(lambda x: x**2, numbers))
print(squares)  # Output: [1, 4, 9, 16, 25]

# 9. filter() - Filters the elements of a list based on a function.
numbers = [1, 2, 3, 4, 5]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print(even_numbers)  # Output: [2, 4]

# 10. zip() - Combines two or more lists into a single list of tuples.
fruits = ["apple", "banana", "cherry"]
colors = ["red", "yellow", "blue"]
zipped = list(zip(fruits, colors))
print(zipped)  # Output: [('apple', 'red'), ('banana', 'yellow'), ('cherry', 'blue')]

# 11. any() - Returns True if any element of a list is True.
numbers = [0, 1, 2, 3, 4]
result = any(numbers)
print(result)  # Output: True


['apple', 'banana', 'cherry', 'orange']
3
2
2
['apple', 'cherry']
['apple', 'banana', 'cherry']
['cherry', 'banana', 'apple']
['apple', 'banana', 'cherry', 'Ford', 'BMW', 'Volvo']
['apple', 'orange', 'banana', 'cherry']
['apple', 'cherry']
['apple', 'banana', 'cherry']
[]
5
1
15
Hello world !
['Hello', 'world', '!']
1
True
0 apple
1 banana
2 cherry
[1, 4, 9, 16, 25]
[2, 4]
[('apple', 'red'), ('banana', 'yellow'), ('cherry', 'blue')]
True


## Math Module

In [ ]:
import math

# 1. ceil(): returns the smallest integer greater than or equal to a given number
x = 4.1
print(math.ceil(x))  # Output: 5

# 2. floor(): returns the largest integer less than or equal to a given number
y = 4.9
print(math.floor(y))  # Output: 4

# 3. fabs(): returns the absolute value of a given number
a = -4.5
print(math.fabs(a))  # Output: 4.5

# 4. sqrt(): returns the square root of a given number
b = 16
print(math.sqrt(b))  # Output: 4.0

# 5. pow(): returns the value of a number raised to a power
c = 2
d = 3
print(math.pow(c, d))  # Output: 8.0

# 6. exp(): returns the value of e (Euler's number) raised to a power
e = 2
print(math.exp(e))  # Output: 7.38905609893065

# 7. log(): returns the natural logarithm of a number
f = 10
print(math.log(f))  # Output: 2.302585092994046

# 8. log10(): returns the base-10 logarithm of a number
g = 100
print(math.log10(g))  # Output: 2.0

# 9. sin(): returns the sine of a given angle in radians
h = math.pi/2
print(math.sin(h))  # Output: 1.0

# 10. cos(): returns the cosine of a given angle in radians
i = math.pi
print(math.pi) # Output: 3.141592653589793
print(math.cos(i))  # Output: -1.0

# 11. tan(): returns the tangent of a given angle in radians
j = math.pi/4
print(math.tan(j))  # Output: 0.9999999999999999

# 12. degrees(): converts an angle from radians to degrees
k = math.pi/2
print(math.degrees(k))  # Output: 90.0

# 13. radians(): converts an angle from degrees to radians
l = 180
print(math.radians(l))  # Output: 3.141592653589793

# 14. factorial(): returns the factorial of a given number
m = 5
print(math.factorial(m))  # Output: 120

# 15. gcd(): returns the greatest common divisor of two numbers
n = 12
o = 16
print(math.gcd(n, o))  # Output: 4


5
4
4.5
4.0
8.0
7.38905609893065
2.302585092994046
2.0
1.0
3.141592653589793
-1.0
0.9999999999999999
90.0
3.141592653589793
120
4


# Numpy

examples for NumPy Creating Arrays, NumPy Array Indexing, and NumPy Array Slicing

In [4]:
import numpy as np

# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Printing the array
print("Original array:", arr)

# Selecting a single element
print("Element at index 2:", arr[2])

# Selecting a range of elements using slicing
print("Elements from index 1 to 3:", arr[1:4])

# Selecting every other element using slicing
print("Every other element:", arr[::2])

# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Printing the array
print("Original 2D array:\n", arr_2d)

# Selecting a single element
print("Element at row 1, column 2:", arr_2d[1, 2])

# Selecting a row using slicing
print("Row 2:", arr_2d[1, :])

# Selecting a column using slicing
print("Column 3:", arr_2d[:, 2])

# Selecting a subarray using slicing
print("Subarray at row 1 and 2, column 2 and 3:\n", arr_2d[1:3, 1:3])


Original array: [1 2 3 4 5]
Element at index 2: 3
Elements from index 1 to 3: [2 3 4]
Every other element: [1 3 5]
Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
Row 2: [4 5 6]
Column 3: [3 6 9]
Subarray at row 1 and 2, column 2 and 3:
 [[5 6]
 [8 9]]


In [1]:
import numpy as np

# NumPy Creating Arrays
# Creating an array from a list
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

# Creating an array of zeros
zeros_array = np.zeros(5)
print(zeros_array)

# Creating an array of ones
ones_array = np.ones(5)
print(ones_array)

# NumPy Array Indexing
# Accessing an element in a 1D array
print(my_array[2])

# Accessing an element in a 2D array
my_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_2d_array[1][2])

# NumPy Array Slicing
# Slicing a 1D array
print(my_array[1:4])

# Slicing a 2D array
print(my_2d_array[:2, 1:])

# NumPy Data Types
# Specifying data types for an array
my_int_array = np.array([1, 2, 3], dtype=int)
print(my_int_array)
my_float_array = np.array([1.1, 2.2, 3.3], dtype=float)
print(my_float_array)

# NumPy Copy vs View
# Creating a copy of an array
my_copy = my_array.copy()
my_copy[2] = 10
print(my_copy)
print(my_array)

# Creating a view of an array
my_view = my_array.view()
my_view[2] = 10
print(my_view)
print(my_array)

# NumPy Array Shape
# Getting the shape of an array
print(my_2d_array.shape)

# NumPy Array Reshape
# Reshaping an array
my_reshaped_array = my_array.reshape((5, 1))
print(my_reshaped_array)

# NumPy Array Iterating
# Iterating over a 1D array
for element in my_array:
    print(element)

# Iterating over a 2D array
for row in my_2d_array:
    for element in row:
        print(element)

# NumPy Array Join
# Joining two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
joined_array = np.concatenate((array1, array2))
print(joined_array)

# NumPy Array Split
# Splitting an array
split_array = np.array_split(joined_array, 2)
print(split_array)

# NumPy Array Search
# Searching for an element in an array
print(np.where(my_array == 3))

# NumPy Array Sort
# Sorting an array
sorted_array = np.sort(my_array)
print(sorted_array)

# NumPy Array Filter
# Filtering an array
filtered_array = my_array[my_array > 3]
print(filtered_array)


[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
3
6
[2 3 4]
[[2 3]
 [5 6]]
[1 2 3]
[1.1 2.2 3.3]
[ 1  2 10  4  5]
[1 2 3 4 5]
[ 1  2 10  4  5]
[ 1  2 10  4  5]
(3, 3)
[[ 1]
 [ 2]
 [10]
 [ 4]
 [ 5]]
1
2
10
4
5
1
2
3
4
5
6
7
8
9
[1 2 3 4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]
(array([], dtype=int64),)
[ 1  2  4  5 10]
[10  4  5]


In [2]:
import numpy as np

# Creating Arrays
arr = np.array([1, 2, 3, 4, 5])
print("Creating Arrays:")
print(arr)

# Array Indexing
print("\nArray Indexing:")
print(arr[0])
print(arr[2])

# Array Slicing
print("\nArray Slicing:")
print(arr[1:4])

# Data Types
print("\nData Types:")
print(arr.dtype)

# Copy vs View
print("\nCopy vs View:")
arr_copy = arr.copy()
arr_view = arr.view()
print(arr_copy)
print(arr_view)

# Array Shape
print("\nArray Shape:")
print(arr.shape)

# Array Reshape
print("\nArray Reshape:")
arr_reshape = arr.reshape(1, 5)
print(arr_reshape)

# Array Iterating
print("\nArray Iterating:")
for x in arr:
  print(x)

# Array Join
print("\nArray Join:")
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_join = np.concatenate((arr_1, arr_2))
print(arr_join)

# Array Split
print("\nArray Split:")
arr_split = np.array_split(arr_join, 2)
print(arr_split)

# Array Search
print("\nArray Search:")
print(np.where(arr == 3))

# Array Sort
print("\nArray Sort:")
arr_sort = np.array([3, 1, 2, 5, 4])
print(np.sort(arr_sort))

# Array Filter
print("\nArray Filter:")
arr_filter = np.array([1, 2, 3, 4, 5])
arr_filtered = arr_filter[arr_filter > 3]
print(arr_filtered)



Creating Arrays:
[1 2 3 4 5]

Array Indexing:
1
3

Array Slicing:
[2 3 4]

Data Types:
int64

Copy vs View:
[1 2 3 4 5]
[1 2 3 4 5]

Array Shape:
(5,)

Array Reshape:
[[1 2 3 4 5]]

Array Iterating:
1
2
3
4
5

Array Join:
[1 2 3 4 5 6]

Array Split:
[array([1, 2, 3]), array([4, 5, 6])]

Array Search:
(array([2]),)

Array Sort:
[1 2 3 4 5]

Array Filter:
[4 5]
