<a href="https://colab.research.google.com/github/ia234/Python_23/blob/main/Python_Cheat_Sheet_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python

## Data Types

Numeric Data Types:

In [ ]:
# integer
my_int = 10
print(type(my_int))  # Output: <class 'int'>

# floating-point number
my_float = 3.14
print(type(my_float))  # Output: <class 'float'>

# complex number
my_complex = 2 + 3j
print(type(my_complex))  # Output: <class 'complex'>


<class 'int'>
<class 'float'>
<class 'complex'>


Sequence Data Types:

In [ ]:
# string
my_string = "Hello, World!"
print(type(my_string))  # Output: <class 'str'>

# list This is a collection of items that are ordered and changeable.
my_list = [1, 2, "three", True]
print(type(my_list))  # Output: <class 'list'>

# tuple This is a collection of items that are ordered and unchangeable.
my_tuple = (1, 2, "three", True)
print(type(my_tuple))  # Output: <class 'tuple'>

# range The range function is used to create a sequence of numbers, and it returns a range object. 
my_range = range(5)
print(type(my_range))  # Output: <class 'range'>



<class 'str'>
<class 'list'>
<class 'tuple'>
<class 'range'>


Mapping Data Type:

In [ ]:
# dictionary: This is a collection of key-value pairs that are unordered and changeable.
my_dict = {"name": "John", "age": 30, "city": "New York"}
print(type(my_dict))  # Output: <class 'dict'>


<class 'dict'>


Set Data Type:

In [ ]:
# set: This is a collection of unique items that are unordered and unindexed.
my_set = {1, 2, "three", True}
print(type(my_set))  # Output: <class 'set'>


# frozenset The frozenset function is used to create an immutable set, and it returns a frozenset object.
my_frozenset = frozenset({1, 2, 3})
print(type(my_frozenset))  # Output: <class 'frozenset'>


<class 'set'>
<class 'frozenset'>


**Boolean Data Type:**

In [ ]:
# boolean: This is a data type that represents True or False values.
my_bool = True
print(type(my_bool))  # Output: <class 'bool'>


<class 'bool'>


This expression compares the Unicode code point of the characters in the strings, and returns a boolean value True or False depending on the result of the comparison.
In this case, "alpha" comes before "beta" in alphabetical order, so the expression evaluates to True.
These operators and functions can be used in combination with logical operators such as "and", "or", and "not" to create more complex comparisons.

In [ ]:
print("alpha" <= "beta")

print(True > False)

True
True


In [1]:
x = 10

if x > 10:
    print("x is greater than 10")
elif x < 10:
    print("x is less than 10")
else:
    print("x is equal to 10")


x is equal to 10


## Arithmetic Operators

In [ ]:
x = 9
y = 7

# Addition
z = x + y  # add x and y
print(z)

# Subtraction
z = x - y  # subtract y from x
print(z)

# Multiplication
z = x * y  # multiply x and y
print(z)

# Division
z = x / y  # divide x by y
print(z)

# Floor Division
z = x // y  # divide x by y and round down to the nearest integer
print(z)

# Modulus
z = x % y  # find the remainder of x divided by y
print(z)

# Exponentiation
z = x ** y  # raise x to the power of y
print(z)


16
2
63
1.2857142857142858
1
2
4782969


## Lists

### List Subsetting & Slicing

In [ ]:
# Define a list of fruits
fruits = ["apple", "banana", "cherry", "date", "elderberry"]

# Access a single element using its index (starts at 0)
print(fruits[0])    # Output: "apple"
print(fruits[2])    # Output: "cherry"

# Access a range of elements using a slice
print(fruits[1:4])  # Output: ["banana", "cherry", "date"]
print(fruits[:3])   # Output: ["apple", "banana", "cherry"]
print(fruits[3:])   # Output: ["date", "elderberry"]

# Access elements from the end of the list using negative indexing
print(fruits[-1])   # Output: "elderberry"
print(fruits[-3:])  # Output: ["cherry", "date", "elderberry"]




apple
cherry
['banana', 'cherry', 'date']
['apple', 'banana', 'cherry']
['date', 'elderberry']
elderberry
['cherry', 'date', 'elderberry']


### List operations and Functions

In [ ]:
# Check if Item Exists
if "apple" in fruits:
    print("Yes, 'apple' is in the fruits list")  # Output: "Yes, 'apple' is in the fruits list"

# Access List Items
for fruit in fruits:
    print(fruit)  # Output: "apple", "banana", "cherry"

# Change List Items
fruits[1] = "kiwi"
print(fruits)  # Output: ["apple", "kiwi", "cherry"]

# Add List Items
fruits.append("orange")
print(fruits)  # Output: ["apple", "kiwi", "cherry", "orange"]

# Remove List Items
fruits.remove("kiwi")
print(fruits)  # Output: ["apple", "cherry", "orange"]

# Loop Lists
for fruit in fruits:
    print(fruit)  # Output: "apple", "cherry", "orange"

# List Comprehension
new_list = [fruit for fruit in fruits if "a" in fruit]
print(new_list)  # Output: ["apple", "orange"]

# Sort Lists
fruits.sort()
print(fruits)  # Output: ["apple", "cherry", "orange"]

# Copy Lists in 3 ways:
# 1. using .copy() method
new_fruits = fruits.copy()
print(new_fruits)  # Output: ["apple", "cherry", "orange"]

# 2. using the list() function
# list_x = list(y) 

# 3. using the slicing operator 
# list_x = list_y[:]

# list_x = list_y copies the pointer to that list which causes any changes to list x to take effect in list y too.


# Join Lists
vegetables = ["beetroot", "carrot", "spinach"]
food = fruits + vegetables
print(food)  # Output: ["apple", "cherry", "orange", "beetroot", "carrot", "spinach"]


Yes, 'apple' is in the fruits list
apple
banana
cherry
date
elderberry
['apple', 'kiwi', 'cherry', 'date', 'elderberry']
['apple', 'kiwi', 'cherry', 'date', 'elderberry', 'orange']
['apple', 'cherry', 'date', 'elderberry', 'orange']
apple
cherry
date
elderberry
orange
['apple', 'date', 'orange']
['apple', 'cherry', 'date', 'elderberry', 'orange']
['apple', 'cherry', 'date', 'elderberry', 'orange']
['apple', 'cherry', 'date', 'elderberry', 'orange', 'beetroot', 'carrot', 'spinach']


### List Methods

Here are 25 of the most frequently used list methods in Python, ranked in order from most frequently used to least frequently used:

1. `append()` - Adds an element to the end of a list.
2. `len()` - Returns the length of a list.
3. `index()` - Returns the index of the first element with the specified value.
4. `count()` - Returns the number of elements with the specified value.
5. `pop()` - Removes the element at the specified position from a list, and returns it.
6. `sort()` - Sorts the elements of a list in ascending order.
7. `reverse()` - Reverses the order of the elements in a list.
8. `extend()` - Adds the elements of another list to the end of a list.
9. `insert()` - Adds an element at the specified position in a list.
10. `remove()` - Removes the first occurrence of a specified element from a list.
11. `copy()` - Returns a shallow copy of a list.
12. `clear()` - Removes all the elements from a list.
13. `max()` - Returns the largest element in a list.
14. `min()` - Returns the smallest element in a list.
15. `sum()` - Returns the sum of all elements in a list.
16. `join()` - Joins the elements of a list into a string.
17. `split()` - Splits a string into a list.
18. 
19. `index()` - Returns the index of the first occurrence of a specified element in a list.
20. `isinstance()` - Returns True if a variable is a list.
21. `enumerate()` - Returns an enumerate object.
22. `map()` - Applies a function to every element of a list.
23. `filter()` - Filters the elements of a list based on a function.
24. `zip()` - Combines two or more lists into a single list of tuples.
25. `any()` - Returns True if any element of a list is True.

In [ ]:
# Here are the 25 most frequently used list methods in Python, ranked in order from most frequently used to least frequently used, with comments and examples:

# 1. append() - Adds an element to the end of a list.
fruits = ["apple", "banana", "cherry"]
fruits.append("orange")
print(fruits) # Output: ["apple", "banana", "cherry", "orange"]

# 2. len() - Returns the length of a list.
fruits = ["apple", "banana", "cherry"]
print(len(fruits)) # Output: 3

# 3. index() - Returns the index of the first element with the specified value.
fruits = ["apple", "banana", "cherry"]
print(fruits.index("cherry")) # Output: 2

# 4. count() - Returns the number of elements with the specified value.
fruits = ["apple", "banana", "cherry", "cherry"]
print(fruits.count("cherry")) # Output: 2

# 5. pop() - Removes the element at the specified position from a list, and returns it.
fruits = ["apple", "banana", "cherry"]
fruits.pop(1)
print(fruits) # Output: ["apple", "cherry"]

# 6. sort() - Sorts the elements of a list in ascending order.
fruits = ["banana", "cherry", "apple"]
fruits.sort()
print(fruits) # Output: ["apple", "banana", "cherry"]

# 7. reverse() - Reverses the order of the elements in a list.
fruits = ["apple", "banana", "cherry"]
fruits.reverse()
print(fruits) # Output: ["cherry", "banana", "apple"]

# 8. extend() - Adds the elements of another list to the end of a list.
fruits = ["apple", "banana", "cherry"]
cars = ["Ford", "BMW", "Volvo"]
fruits.extend(cars)
print(fruits) # Output: ["apple", "banana", "cherry", "Ford", "BMW", "Volvo"]

# 9. insert() - Adds an element at the specified position in a list.
fruits = ["apple", "banana", "cherry"]
fruits.insert(1, "orange")
print(fruits) # Output: ["apple", "orange", "banana", "cherry"]

# 10. remove() - Removes the first occurrence of a specified element from a list.
fruits = ["apple", "banana", "cherry"]
fruits.remove("banana")
print(fruits) # Output: ["apple", "cherry"]

# 11. copy() - Returns a shallow copy of a list.
fruits = ["apple", "banana", "cherry"]
fruits_copy = fruits.copy()
print(fruits_copy) # Output: ["apple", "banana", "cherry"]

# 12. clear() - Removes all the elements from a list.
fruits = ["apple", "banana", "cherry"]
fruits.clear()
print(fruits) # Output: []

# 13. max() - Returns the largest element in a list.
numbers = [1, 2, 3, 4, 5]
print(max(numbers)) # Output: 5

# 14. min() - Returns the smallest element in a list.
numbers = [1, 2, 3, 4, 5]
print(min(numbers)) # Output: 1

# 1. sum() - Returns the sum of all elements in a list.
numbers = [1, 2, 3, 4, 5]
result = sum(numbers)
print(result)  # Output: 15

# 2. join() - Joins the elements of a list into a string.
words = ["Hello", "world", "!"]
result = " ".join(words)
print(result)  # Output: "Hello world !"

# 3. split() - Splits a string into a list.
sentence = "Hello world !"
words = sentence.split()
print(words)  # Output: ["Hello", "world", "!"]

# 4. 

# 5. index() - Returns the index of the first occurrence of a specified element in a list.
fruits = ["apple", "banana", "cherry"]
index = fruits.index("banana")
print(index)  # Output: 1

# 6. isinstance() - Returns True if a variable is a list.
fruits = ["apple", "banana", "cherry"]
result = isinstance(fruits, list)
print(result)  # Output: True

# 7. enumerate() - Returns an enumerate object.
fruits = ["apple", "banana", "cherry"]
for index, value in enumerate(fruits):
    print(index, value)  # Output: 0 apple, 1 banana, 2 cherry

# 8. map() - Applies a function to every element of a list.
numbers = [1, 2, 3, 4, 5]
squares = list(map(lambda x: x**2, numbers))
print(squares)  # Output: [1, 4, 9, 16, 25]

# 9. filter() - Filters the elements of a list based on a function.
numbers = [1, 2, 3, 4, 5]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print(even_numbers)  # Output: [2, 4]

# 10. zip() - Combines two or more lists into a single list of tuples.
fruits = ["apple", "banana", "cherry"]
colors = ["red", "yellow", "blue"]
zipped = list(zip(fruits, colors))
print(zipped)  # Output: [('apple', 'red'), ('banana', 'yellow'), ('cherry', 'blue')]

# 11. any() - Returns True if any element of a list is True.
numbers = [0, 1, 2, 3, 4]
result = any(numbers)
print(result)  # Output: True


['apple', 'banana', 'cherry', 'orange']
3
2
2
['apple', 'cherry']
['apple', 'banana', 'cherry']
['cherry', 'banana', 'apple']
['apple', 'banana', 'cherry', 'Ford', 'BMW', 'Volvo']
['apple', 'orange', 'banana', 'cherry']
['apple', 'cherry']
['apple', 'banana', 'cherry']
[]
5
1
15
Hello world !
['Hello', 'world', '!']
1
True
0 apple
1 banana
2 cherry
[1, 4, 9, 16, 25]
[2, 4]
[('apple', 'red'), ('banana', 'yellow'), ('cherry', 'blue')]
True


## Math Module

In [ ]:
import math

# 1. ceil(): returns the smallest integer greater than or equal to a given number
x = 4.1
print(math.ceil(x))  # Output: 5

# 2. floor(): returns the largest integer less than or equal to a given number
y = 4.9
print(math.floor(y))  # Output: 4

# 3. fabs(): returns the absolute value of a given number
a = -4.5
print(math.fabs(a))  # Output: 4.5

# 4. sqrt(): returns the square root of a given number
b = 16
print(math.sqrt(b))  # Output: 4.0

# 5. pow(): returns the value of a number raised to a power
c = 2
d = 3
print(math.pow(c, d))  # Output: 8.0

# 6. exp(): returns the value of e (Euler's number) raised to a power
e = 2
print(math.exp(e))  # Output: 7.38905609893065

# 7. log(): returns the natural logarithm of a number
f = 10
print(math.log(f))  # Output: 2.302585092994046

# 8. log10(): returns the base-10 logarithm of a number
g = 100
print(math.log10(g))  # Output: 2.0

# 9. sin(): returns the sine of a given angle in radians
h = math.pi/2
print(math.sin(h))  # Output: 1.0

# 10. cos(): returns the cosine of a given angle in radians
i = math.pi
print(math.pi) # Output: 3.141592653589793
print(math.cos(i))  # Output: -1.0

# 11. tan(): returns the tangent of a given angle in radians
j = math.pi/4
print(math.tan(j))  # Output: 0.9999999999999999

# 12. degrees(): converts an angle from radians to degrees
k = math.pi/2
print(math.degrees(k))  # Output: 90.0

# 13. radians(): converts an angle from degrees to radians
l = 180
print(math.radians(l))  # Output: 3.141592653589793

# 14. factorial(): returns the factorial of a given number
m = 5
print(math.factorial(m))  # Output: 120

# 15. gcd(): returns the greatest common divisor of two numbers
n = 12
o = 16
print(math.gcd(n, o))  # Output: 4


5
4
4.5
4.0
8.0
7.38905609893065
2.302585092994046
2.0
1.0
3.141592653589793
-1.0
0.9999999999999999
90.0
3.141592653589793
120
4


# Numpy

### Direct arithmetic operations

In [ ]:
import numpy as np

# create two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# add two arrays element-wise
arr_sum = arr1 + arr2
print("Array sum:")
print(arr_sum)

# subtract one array from another element-wise
arr_diff = arr1 - arr2
print("Array difference:")
print(arr_diff)

# multiply two arrays element-wise
arr_product = arr1 * arr2
print("Array product:")
print(arr_product)

# divide one array by another element-wise
arr_quotient = arr1 / arr2
print("Array quotient:")
print(arr_quotient)

# raise one array to the power of another element-wise
arr_power = arr1 ** arr2
print("Array power:")
print(arr_power)


Array sum:
[[ 6  8]
 [10 12]]
Array difference:
[[-4 -4]
 [-4 -4]]
Array product:
[[ 5 12]
 [21 32]]
Array quotient:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
Array power:
[[    1    64]
 [ 2187 65536]]


### Creating Arrays, Indexing, Slicing, and subsetting

In [ ]:
import numpy as np

# NumPy Creating Arrays
# Creating an array from a list
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

# Creating an array of zeros
zeros_array = np.zeros(5)
print(zeros_array)

# Creating an array of ones
ones_array = np.ones(5)
print(ones_array)

# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Printing the array
print("Original array:", arr)

# Selecting a single element
print("Element at index 2:", arr[2])

# Selecting a range of elements using slicing
print("Elements from index 1 to 3:", arr[1:4])

# Selecting every other element using slicing
print("Every other element:", arr[::2])

# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Printing the array
print("Original 2D array:\n", arr_2d)

# Selecting a single element
print("Element at row 1, column 2:", arr_2d[1, 2])

# Selecting a row using slicing
print("Row 2:", arr_2d[1, :])

# Selecting a column using slicing
print("Column 3:", arr_2d[:, 2])

# Selecting a subarray using slicing
print("Subarray at row 1 and 2, column 2 and 3:\n", arr_2d[1:3, 1:3])

# Subsetting the array to get only the values greater than 3
subset_arr = arr[arr > 3]

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
Original array: [1 2 3 4 5]
Element at index 2: 3
Elements from index 1 to 3: [2 3 4]
Every other element: [1 3 5]
Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
Row 2: [4 5 6]
Column 3: [3 6 9]
Subarray at row 1 and 2, column 2 and 3:
 [[5 6]
 [8 9]]


In [ ]:
# boolean indexing: a way to select values from a NumPy array based on a boolean condition.

bmi = np.array([1, 2, 3, 4, 25, 55])

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[ True  True  True  True False False]
[1 2 3 4]


There are several techniques and tricks to select values from a NumPy array:


    Using boolean indexing: You can create a boolean mask to select specific values from a NumPy array based on a condition.

    Using integer indexing: You can use integer indices to select specific rows or columns of a NumPy array.

    Using slicing: You can use the slicing operator : to select a subset of the elements in a NumPy array.

    Using the where() function: You can use the where() function to select values from a NumPy array based on a condition.

    Using the take() function: You can use the take() function to select specific values from a NumPy array based on their index.

    Using the choose() function: You can use the choose() function to select specific values from a NumPy array based on their index.

    Using the compress() function: You can use the compress() function to select specific values from a NumPy array based on a boolean mask.

These techniques can be used in combination to create more complex selection criteria.


### functions for arithmetic operations on 2D arrays

    np.add(): performs element-wise addition of two arrays.
    np.subtract(): performs element-wise subtraction of two arrays.
    np.multiply(): performs element-wise multiplication of two arrays.
    np.divide(): performs element-wise division of two arrays.
    np.dot(): performs dot product of two arrays.
    np.matmul(): performs matrix multiplication of two arrays.
    np.transpose(): transposes the array.
    np.sum(): returns the sum of all elements in the array or along a specific axis.
    np.mean(): returns the mean of all elements in the array or along a specific axis.

In [ ]:
import numpy as np

# creating 2D arrays
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[2, 2, 2], [3, 3, 3], [4, 4, 4]])

# element-wise addition
c = np.add(a, b)
print("Element-wise addition:\n", c)

# element-wise subtraction
d = np.subtract(a, b)
print("Element-wise subtraction:\n", d)

# element-wise multiplication
e = np.multiply(a, b)
print("Element-wise multiplication:\n", e)

# element-wise division
f = np.divide(a, b)
print("Element-wise division:\n", f)

# dot product
g = np.dot(a, b)
print("Dot product:\n", g)

# matrix multiplication
h = np.matmul(a, b)
print("Matrix multiplication:\n", h)

# transpose
i = np.transpose(a)
print("Transpose:\n", i)

# sum along axis 0
j = np.sum(a, axis=0)
print("Sum along axis 0:\n", j)

# sum along axis 1
k = np.sum(a, axis=1)
print("Sum along axis 1:\n", k)


Element-wise addition:
 [[ 3  4  5]
 [ 7  8  9]
 [11 12 13]]
Element-wise subtraction:
 [[-1  0  1]
 [ 1  2  3]
 [ 3  4  5]]
Element-wise multiplication:
 [[ 2  4  6]
 [12 15 18]
 [28 32 36]]
Element-wise division:
 [[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]
 [1.75       2.         2.25      ]]
Dot product:
 [[20 20 20]
 [47 47 47]
 [74 74 74]]
Matrix multiplication:
 [[20 20 20]
 [47 47 47]
 [74 74 74]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum along axis 0:
 [12 15 18]
Sum along axis 1:
 [ 6 15 24]


NumPy functions that perform element-wise logical operations on arrays:
`np.logical_and()`, `np.logical_or()`, and `np.logical_not()` 



In [ ]:
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

np.logical_and(my_house > 13, 
               your_house < 15)

array([ True, False, False, False])

### NumPy statistical functions 

    numpy.mean(): Calculates the arithmetic mean of the elements in the array.
    numpy.median(): Calculates the median of the elements in the array.
    numpy.std(): Calculates the standard deviation of the elements in the array.
    numpy.var(): Calculates the variance of the elements in the array.
    numpy.min(): Finds the minimum value of the elements in the array.
    numpy.max(): Finds the maximum value of the elements in the array.

In [ ]:

# mean along axis 0
l = np.mean(a, axis=0)
print("Mean along axis 0:\n", l)

# mean along axis 1
m = np.mean(a, axis=1)
print("Mean along axis 1:\n", m)

# Calculate the median of the array
median = np.median(my_array)
print("The median of the array is:", median)



# Calculate the mean of the array
mean = np.mean(arr)
print("Mean:", mean)  # Output: Mean: 3.0

# Calculate the median of the array
median = np.median(arr)
print("Median:", median)  # Output: Median: 3.0

# Calculate the standard deviation of the array
std = np.std(arr)
print("Standard deviation:", std)  # Output: Standard deviation: 1.4142135623730951

# Calculate the variance of the array
var = np.var(arr)
print("Variance:", var)  # Output: Variance: 2.0

# Find the minimum value of the array
min_val = np.min(arr)
print("Minimum value:", min_val)  # Output: Minimum value: 1

# Find the maximum value of the array
max_val = np.max(arr)
print("Maximum value:", max_val)  # Output: Maximum value: 5

# Correlation coefficient
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[2, 4, 6], [1, 3, 5], [3, 6, 9]])
corr_coef = np.corrcoef(arr, arr2)
print("Correlation coefficient:\n", corr_coef)


Mean along axis 0:
 [4. 5. 6.]
Mean along axis 1:
 [2. 5. 8.]
The median of the array is: 3.0
Mean: 3.0
Median: 3.0
Standard deviation: 1.4142135623730951
Variance: 2.0
Minimum value: 1
Maximum value: 5
Correlation coefficient:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
