<a href="https://colab.research.google.com/github/ia234/Python_23/blob/main/Python_Cheat_Sheet_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Python

## Data Types

Numeric Data Types:

In [2]:
# integer
my_int = 10
print(type(my_int))  # Output: <class 'int'>

# floating-point number
my_float = 3.14
print(type(my_float))  # Output: <class 'float'>

# complex number
my_complex = 2 + 3j
print(type(my_complex))  # Output: <class 'complex'>


<class 'int'>
<class 'float'>
<class 'complex'>


Sequence Data Types:

In [3]:
# string
my_string = "Hello, World!"
print(type(my_string))  # Output: <class 'str'>

# list This is a collection of items that are ordered and changeable.
my_list = [1, 2, "three", True]
print(type(my_list))  # Output: <class 'list'>

# tuple This is a collection of items that are ordered and unchangeable.
my_tuple = (1, 2, "three", True)
print(type(my_tuple))  # Output: <class 'tuple'>

# range The range function is used to create a sequence of numbers, and it returns a range object.
my_range = range(5)
print(type(my_range))  # Output: <class 'range'>



<class 'str'>
<class 'list'>
<class 'tuple'>
<class 'range'>


Mapping Data Type:

In [4]:
# dictionary: This is a collection of key-value pairs that are unordered and changeable.
my_dict = {"name": "John", "age": 30, "city": "New York"}
print(type(my_dict))  # Output: <class 'dict'>


<class 'dict'>


Set Data Type:

In [5]:
# set: This is a collection of unique items that are unordered and unindexed.
my_set = {1, 2, "three", True}
print(type(my_set))  # Output: <class 'set'>


# frozenset The frozenset function is used to create an immutable set, and it returns a frozenset object.
my_frozenset = frozenset({1, 2, 3})
print(type(my_frozenset))  # Output: <class 'frozenset'>


<class 'set'>
<class 'frozenset'>


**Boolean Data Type:**

In [6]:
# boolean: This is a data type that represents True or False values.
my_bool = True
print(type(my_bool))  # Output: <class 'bool'>


<class 'bool'>


This expression compares the Unicode code point of the characters in the strings, and returns a boolean value True or False depending on the result of the comparison.
In this case, "alpha" comes before "beta" in alphabetical order, so the expression evaluates to True.
These operators and functions can be used in combination with logical operators such as "and", "or", and "not" to create more complex comparisons.

In [7]:
print("alpha" <= "beta")

print(True > False)

True
True


In [8]:
age = 30
gender = 'female'

# Check eligibility for a certain discount based on age and gender
if age >= 60 and gender == 'female':
    print("You are eligible for a 30% discount!")
elif age >= 60 or gender == 'male':
    print("You are eligible for a 20% discount!")
else:
    print("You are not eligible for any discount.")

You are not eligible for any discount.


## Arithmetic Operators

In [9]:
x = 9
y = 7

# Addition
z = x + y  # add x and y
print(z)

# Subtraction
z = x - y  # subtract y from x
print(z)

# Multiplication
z = x * y  # multiply x and y
print(z)

# Division
z = x / y  # divide x by y
print(z)

# Floor Division
z = x // y  # divide x by y and round down to the nearest integer
print(z)

# Modulus
z = x % y  # find the remainder of x divided by y
print(z)

# Exponentiation
z = x ** y  # raise x to the power of y
print(z)


16
2
63
1.2857142857142858
1
2
4782969


## Lists

### List Subsetting & Slicing

In [10]:
# Define a list of fruits
fruits = ["apple", "banana", "cherry", "date", "elderberry"]

# Access a single element using its index (starts at 0)
print(fruits[0])    # Output: "apple"
print(fruits[2])    # Output: "cherry"

# Access a range of elements using a slice
print(fruits[1:4])  # Output: ["banana", "cherry", "date"]
print(fruits[:3])   # Output: ["apple", "banana", "cherry"]
print(fruits[3:])   # Output: ["date", "elderberry"]

# Access elements from the end of the list using negative indexing
print(fruits[-1])   # Output: "elderberry"
print(fruits[-3:])  # Output: ["cherry", "date", "elderberry"]




apple
cherry
['banana', 'cherry', 'date']
['apple', 'banana', 'cherry']
['date', 'elderberry']
elderberry
['cherry', 'date', 'elderberry']


### List operations and Functions

In [11]:
# Check if Item Exists
if "apple" in fruits:
    print("Yes, 'apple' is in the fruits list")  # Output: "Yes, 'apple' is in the fruits list"

# Access List Items
for fruit in fruits:
    print(fruit)  # Output: "apple", "banana", "cherry"

# Change List Items
fruits[1] = "kiwi"
print(fruits)  # Output: ["apple", "kiwi", "cherry"]

# Add List Items
fruits.append("orange")
print(fruits)  # Output: ["apple", "kiwi", "cherry", "orange"]

# Remove List Items
fruits.remove("kiwi")
print(fruits)  # Output: ["apple", "cherry", "orange"]

# Loop Lists
for fruit in fruits:
    print(fruit)  # Output: "apple", "cherry", "orange"

# List Comprehension
new_list = [fruit for fruit in fruits if "a" in fruit]
print(new_list)  # Output: ["apple", "orange"]

# Sort Lists
fruits.sort()
print(fruits)  # Output: ["apple", "cherry", "orange"]

# Copy Lists in 3 ways:
# 1. using .copy() method
new_fruits = fruits.copy()
print(new_fruits)  # Output: ["apple", "cherry", "orange"]

# 2. using the list() function
# list_x = list(y)

# 3. using the slicing operator
# list_x = list_y[:]

# list_x = list_y copies the pointer/reference to that list which causes any changes to list x to take effect in list y too.


# Join Lists
vegetables = ["beetroot", "carrot", "spinach"]
food = fruits + vegetables
print(food)  # Output: ["apple", "cherry", "orange", "beetroot", "carrot", "spinach"]


Yes, 'apple' is in the fruits list
apple
banana
cherry
date
elderberry
['apple', 'kiwi', 'cherry', 'date', 'elderberry']
['apple', 'kiwi', 'cherry', 'date', 'elderberry', 'orange']
['apple', 'cherry', 'date', 'elderberry', 'orange']
apple
cherry
date
elderberry
orange
['apple', 'date', 'orange']
['apple', 'cherry', 'date', 'elderberry', 'orange']
['apple', 'cherry', 'date', 'elderberry', 'orange']
['apple', 'cherry', 'date', 'elderberry', 'orange', 'beetroot', 'carrot', 'spinach']


### List Methods

Here are 25 of the most frequently used list methods in Python, ranked in order from most frequently used to least frequently used:

1. `append()` - Adds an element to the end of a list.
2. `len()` - Returns the length of a list.
3. `index()` - Returns the index of the first element with the specified value.
4. `count()` - Returns the number of elements with the specified value.
5. `pop()` - Removes the element at the specified position from a list, and returns it.
6. `sort()` - Sorts the elements of a list in ascending order.
7. `reverse()` - Reverses the order of the elements in a list.
8. `extend()` - Adds the elements of another list to the end of a list.
9. `insert()` - Adds an element at the specified position in a list.
10. `remove()` - Removes the first occurrence of a specified element from a list.
11. `copy()` - Returns a shallow copy of a list.
12. `clear()` - Removes all the elements from a list.
13. `max()` - Returns the largest element in a list.
14. `min()` - Returns the smallest element in a list.
15. `sum()` - Returns the sum of all elements in a list.
16. `join()` - Joins the elements of a list into a string.
17. `split()` - Splits a string into a list.
18.
19. `index()` - Returns the index of the first occurrence of a specified element in a list.
20. `isinstance()` - Returns True if a variable is a list.
21. `enumerate()` - Returns an enumerate object.
22. `map()` - Applies a function to every element of a list.
23. `filter()` - Filters the elements of a list based on a function.
24. `zip()` - Combines two or more lists into a single list of tuples.
25. `any()` - Returns True if any element of a list is True.

In [12]:
# Here are the 25 most frequently used list methods in Python, ranked in order from most frequently used to least frequently used, with comments and examples:

# 1. append() - Adds an element to the end of a list.
fruits = ["apple", "banana", "cherry"]
fruits.append("orange")
print(fruits) # Output: ["apple", "banana", "cherry", "orange"]

# 2. len() - Returns the length of a list.
fruits = ["apple", "banana", "cherry"]
print(len(fruits)) # Output: 3

# 3. index() - Returns the index of the first element with the specified value.
fruits = ["apple", "banana", "cherry"]
print(fruits.index("cherry")) # Output: 2

# 4. count() - Returns the number of elements with the specified value.
fruits = ["apple", "banana", "cherry", "cherry"]
print(fruits.count("cherry")) # Output: 2

# 5. pop() - Removes the element at the specified position from a list, and returns it.
fruits = ["apple", "banana", "cherry"]
fruits.pop(1)
print(fruits) # Output: ["apple", "cherry"]

# 6. sort() - Sorts the elements of a list in ascending order.
fruits = ["banana", "cherry", "apple"]
fruits.sort()
print(fruits) # Output: ["apple", "banana", "cherry"]

# 7. reverse() - Reverses the order of the elements in a list.
fruits = ["apple", "banana", "cherry"]
fruits.reverse()
print(fruits) # Output: ["cherry", "banana", "apple"]

# 8. extend() - Adds the elements of another list to the end of a list.
fruits = ["apple", "banana", "cherry"]
cars = ["Ford", "BMW", "Volvo"]
fruits.extend(cars)
print(fruits) # Output: ["apple", "banana", "cherry", "Ford", "BMW", "Volvo"]

# 9. insert() - Adds an element at the specified position in a list.
fruits = ["apple", "banana", "cherry"]
fruits.insert(1, "orange")
print(fruits) # Output: ["apple", "orange", "banana", "cherry"]

# 10. remove() - Removes the first occurrence of a specified element from a list.
fruits = ["apple", "banana", "cherry"]
fruits.remove("banana")
print(fruits) # Output: ["apple", "cherry"]

# 11. copy() - Returns a shallow copy of a list.
fruits = ["apple", "banana", "cherry"]
fruits_copy = fruits.copy()
print(fruits_copy) # Output: ["apple", "banana", "cherry"]

# 12. clear() - Removes all the elements from a list.
fruits = ["apple", "banana", "cherry"]
fruits.clear()
print(fruits) # Output: []

# 13. max() - Returns the largest element in a list.
numbers = [1, 2, 3, 4, 5]
print(max(numbers)) # Output: 5

# 14. min() - Returns the smallest element in a list.
numbers = [1, 2, 3, 4, 5]
print(min(numbers)) # Output: 1

# 1. sum() - Returns the sum of all elements in a list.
numbers = [1, 2, 3, 4, 5]
result = sum(numbers)
print(result)  # Output: 15

# 2. join() - Joins the elements of a list into a string.
words = ["Hello", "world", "!"]
result = " ".join(words)
print(result)  # Output: "Hello world !"

# 3. split() - Splits a string into a list.
sentence = "Hello world !"
words = sentence.split()
print(words)  # Output: ["Hello", "world", "!"]

# 4.

# 5. index() - Returns the index of the first occurrence of a specified element in a list.
fruits = ["apple", "banana", "cherry"]
index = fruits.index("banana")
print(index)  # Output: 1

# 6. isinstance() - Returns True if a variable is a list.
fruits = ["apple", "banana", "cherry"]
result = isinstance(fruits, list)
print(result)  # Output: True

# 7. enumerate() - Returns an enumerate object.
fruits = ["apple", "banana", "cherry"]
for index, value in enumerate(fruits):
    print(index, value)  # Output: 0 apple, 1 banana, 2 cherry

# 8. map() - Applies a function to every element of a list.
numbers = [1, 2, 3, 4, 5]
squares = list(map(lambda x: x**2, numbers))
print(squares)  # Output: [1, 4, 9, 16, 25]

# 9. filter() - Filters the elements of a list based on a function.
numbers = [1, 2, 3, 4, 5]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print(even_numbers)  # Output: [2, 4]

# 10. zip() - Combines two or more lists into a single list of tuples.
fruits = ["apple", "banana", "cherry"]
colors = ["red", "yellow", "blue"]
zipped = list(zip(fruits, colors))
print(zipped)  # Output: [('apple', 'red'), ('banana', 'yellow'), ('cherry', 'blue')]

# 11. any() - Returns True if any element of a list is True.
numbers = [0, 1, 2, 3, 4]
result = any(numbers)
print(result)  # Output: True


['apple', 'banana', 'cherry', 'orange']
3
2
2
['apple', 'cherry']
['apple', 'banana', 'cherry']
['cherry', 'banana', 'apple']
['apple', 'banana', 'cherry', 'Ford', 'BMW', 'Volvo']
['apple', 'orange', 'banana', 'cherry']
['apple', 'cherry']
['apple', 'banana', 'cherry']
[]
5
1
15
Hello world !
['Hello', 'world', '!']
1
True
0 apple
1 banana
2 cherry
[1, 4, 9, 16, 25]
[2, 4]
[('apple', 'red'), ('banana', 'yellow'), ('cherry', 'blue')]
True


## Iteration over sequences with 'for' loop

iterating over a list of lists


In [13]:
#  list of lists
house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["bedroom", 10.75],
         ["bathroom", 9.50]]

# Build a for loop from scratch
for room, area in house:
    print('the', room, 'is', area, 'sqm')

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm


iterating over a list and its indicies using the "enumerate()" funtion

In [14]:
# Loop through each row of the list and print the index and row elements
for i, row in enumerate(house):
    print("Index:", i, ', Row:', row)

Index: 0 , Row: ['hallway', 11.25]
Index: 1 , Row: ['kitchen', 18.0]
Index: 2 , Row: ['living room', 20.0]
Index: 3 , Row: ['bedroom', 10.75]
Index: 4 , Row: ['bathroom', 9.5]


iterating over a dictionary using the ".items()" method.

In [15]:
# Definition of dictionary
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw', 'austria':'vienna' }

# Iterate over europe
for key, value in europe.items() :
    print("the capital of", key + " is " + str(value))


the capital of spain is madrid
the capital of france is paris
the capital of germany is berlin
the capital of norway is oslo
the capital of italy is rome
the capital of poland is warsaw
the capital of austria is vienna


iterating over a 1-dimensional NumPy array

In [16]:
import numpy as np
data = np.array([1, 2, 3, 4, 5, 6])
for i in data:
    print(i, "inches")

1 inches
2 inches
3 inches
4 inches
5 inches
6 inches


iterating over a multdimensional NumPy array using the 'np.nditer()' function.

In [17]:
# Create a 2D numpy array
import numpy as np
data = np.array([
                [1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]
                ])

# Loop through each element of the numpy array and print the element
for i in np.nditer(data):
    print(i)

1
2
3
4
5
6
7
8
9


interating over a Pandas DataFrame using the '.iterrows()' method.

In [18]:
import pandas as pd
# index_col = 0 specify the first column as the index.
cars = pd.read_csv('https://assets.datacamp.com/production/repositories/287/datasets/79b3c22c47a2f45a800c62cae39035ff2ea4e609/cars.csv', index_col = 0)
cars

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [19]:
for lab, row in cars.iterrows() :
    print(lab, ':', row['cars_per_cap'])

US : 809
AUS : 731
JAP : 588
IN : 18
RU : 200
MOR : 70
EG : 45


## Math Module

In [20]:
import math

# 1. ceil(): returns the smallest integer greater than or equal to a given number
x = 4.1
print(math.ceil(x))  # Output: 5

# 2. floor(): returns the largest integer less than or equal to a given number
y = 4.9
print(math.floor(y))  # Output: 4

# 3. fabs(): returns the absolute value of a given number
a = -4.5
print(math.fabs(a))  # Output: 4.5

# 4. sqrt(): returns the square root of a given number
b = 16
print(math.sqrt(b))  # Output: 4.0

# 5. pow(): returns the value of a number raised to a power
c = 2
d = 3
print(math.pow(c, d))  # Output: 8.0

# 6. exp(): returns the value of e (Euler's number) raised to a power
e = 2
print(math.exp(e))  # Output: 7.38905609893065

# 7. log(): returns the natural logarithm of a number
f = 10
print(math.log(f))  # Output: 2.302585092994046

# 8. log10(): returns the base-10 logarithm of a number
g = 100
print(math.log10(g))  # Output: 2.0

# 9. sin(): returns the sine of a given angle in radians
h = math.pi/2
print(math.sin(h))  # Output: 1.0

# 10. cos(): returns the cosine of a given angle in radians
i = math.pi
print(math.pi) # Output: 3.141592653589793
print(math.cos(i))  # Output: -1.0

# 11. tan(): returns the tangent of a given angle in radians
j = math.pi/4
print(math.tan(j))  # Output: 0.9999999999999999

# 12. degrees(): converts an angle from radians to degrees
k = math.pi/2
print(math.degrees(k))  # Output: 90.0

# 13. radians(): converts an angle from degrees to radians
l = 180
print(math.radians(l))  # Output: 3.141592653589793

# 14. factorial(): returns the factorial of a given number
m = 5
print(math.factorial(m))  # Output: 120

# 15. gcd(): returns the greatest common divisor of two numbers
n = 12
o = 16
print(math.gcd(n, o))  # Output: 4


5
4
4.5
4.0
8.0
7.38905609893065
2.302585092994046
2.0
1.0
3.141592653589793
-1.0
0.9999999999999999
90.0
3.141592653589793
120
4


# Numpy

### Direct arithmetic operations

In [21]:
import numpy as np

# create two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# add two arrays element-wise
arr_sum = arr1 + arr2
print("Array sum:")
print(arr_sum)

# subtract one array from another element-wise
arr_diff = arr1 - arr2
print("Array difference:")
print(arr_diff)

# multiply two arrays element-wise
arr_product = arr1 * arr2
print("Array product:")
print(arr_product)

# divide one array by another element-wise
arr_quotient = arr1 / arr2
print("Array quotient:")
print(arr_quotient)

# raise one array to the power of another element-wise
arr_power = arr1 ** arr2
print("Array power:")
print(arr_power)


Array sum:
[[ 6  8]
 [10 12]]
Array difference:
[[-4 -4]
 [-4 -4]]
Array product:
[[ 5 12]
 [21 32]]
Array quotient:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
Array power:
[[    1    64]
 [ 2187 65536]]


### Creating Arrays, Indexing, Slicing, and subsetting

In [22]:
import numpy as np

# NumPy Creating Arrays
# Creating an array from a list
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

# Creating an array of zeros
zeros_array = np.zeros(5)
print(zeros_array)

# Creating an array of ones
ones_array = np.ones(5)
print(ones_array)

# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Printing the array
print("Original array:", arr)

# Selecting a single element
print("Element at index 2:", arr[2])

# Selecting a range of elements using slicing
print("Elements from index 1 to 3:", arr[1:4])

# Selecting every other element using slicing
print("Every other element:", arr[::2])

# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Printing the array
print("Original 2D array:\n", arr_2d)

# Selecting a single element
print("Element at row 1, column 2:", arr_2d[1, 2])

# Selecting a row using slicing
print("Row 2:", arr_2d[1, :])

# Selecting a column using slicing
print("Column 3:", arr_2d[:, 2])

# Selecting a subarray using slicing
print("Subarray at row 1 and 2, column 2 and 3:\n", arr_2d[1:3, 1:3])

# Subsetting the array to get only the values greater than 3
subset_arr = arr[arr > 3]

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
Original array: [1 2 3 4 5]
Element at index 2: 3
Elements from index 1 to 3: [2 3 4]
Every other element: [1 3 5]
Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 6
Row 2: [4 5 6]
Column 3: [3 6 9]
Subarray at row 1 and 2, column 2 and 3:
 [[5 6]
 [8 9]]


In [23]:
# boolean indexing: a way to select values from a NumPy array based on a boolean condition.

bmi = np.array([1, 2, 3, 4, 25, 55])

# Create the light array
light = bmi < 21

# Print out light
# print(light)
print(bmi < 21)

# Print out BMIs of all baseball players whose BMI is below 21
# print(bmi[light])
print(bmi[bmi < 21])

[ True  True  True  True False False]
[1 2 3 4]


There are several techniques and tricks to select values from a NumPy array:


    Using boolean indexing: You can create a boolean mask to select specific values from a NumPy array based on a condition.

    Using integer indexing: You can use integer indices to select specific rows or columns of a NumPy array.

    Using slicing: You can use the slicing operator : to select a subset of the elements in a NumPy array.

    Using the where() function: You can use the where() function to select values from a NumPy array based on a condition.

    Using the take() function: You can use the take() function to select specific values from a NumPy array based on their index.

    Using the choose() function: You can use the choose() function to select specific values from a NumPy array based on their index.

    Using the compress() function: You can use the compress() function to select specific values from a NumPy array based on a boolean mask.

These techniques can be used in combination to create more complex selection criteria.


### functions for arithmetic operations on 2D arrays

    np.add(): performs element-wise addition of two arrays.
    np.subtract(): performs element-wise subtraction of two arrays.
    np.multiply(): performs element-wise multiplication of two arrays.
    np.divide(): performs element-wise division of two arrays.
    np.dot(): performs dot product of two arrays.
    np.matmul(): performs matrix multiplication of two arrays.
    np.transpose(): transposes the array.
    np.sum(): returns the sum of all elements in the array or along a specific axis.
    np.mean(): returns the mean of all elements in the array or along a specific axis.

In [24]:
import numpy as np

# creating 2D arrays
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[2, 2, 2], [3, 3, 3], [4, 4, 4]])

# element-wise addition
c = np.add(a, b)
print("Element-wise addition:\n", c)

# element-wise subtraction
d = np.subtract(a, b)
print("Element-wise subtraction:\n", d)

# element-wise multiplication
e = np.multiply(a, b)
print("Element-wise multiplication:\n", e)

# element-wise division
f = np.divide(a, b)
print("Element-wise division:\n", f)

# dot product
g = np.dot(a, b)
print("Dot product:\n", g)

# matrix multiplication
h = np.matmul(a, b)
print("Matrix multiplication:\n", h)

# transpose
i = np.transpose(a)
print("Transpose:\n", i)

# sum along axis 0
j = np.sum(a, axis=0)
print("Sum along axis 0:\n", j)

# sum along axis 1
k = np.sum(a, axis=1)
print("Sum along axis 1:\n", k)


Element-wise addition:
 [[ 3  4  5]
 [ 7  8  9]
 [11 12 13]]
Element-wise subtraction:
 [[-1  0  1]
 [ 1  2  3]
 [ 3  4  5]]
Element-wise multiplication:
 [[ 2  4  6]
 [12 15 18]
 [28 32 36]]
Element-wise division:
 [[0.5        1.         1.5       ]
 [1.33333333 1.66666667 2.        ]
 [1.75       2.         2.25      ]]
Dot product:
 [[20 20 20]
 [47 47 47]
 [74 74 74]]
Matrix multiplication:
 [[20 20 20]
 [47 47 47]
 [74 74 74]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum along axis 0:
 [12 15 18]
Sum along axis 1:
 [ 6 15 24]


NumPy functions that perform element-wise logical operations on arrays:
`np.logical_and()`, `np.logical_or()`, and `np.logical_not()`



In [25]:
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

np.logical_and(my_house > 13,
               your_house < 15)

array([ True, False, False, False])

### NumPy statistical functions

    numpy.mean(): Calculates the arithmetic mean of the elements in the array.
    numpy.median(): Calculates the median of the elements in the array.
    numpy.std(): Calculates the standard deviation of the elements in the array.
    numpy.var(): Calculates the variance of the elements in the array.
    numpy.min(): Finds the minimum value of the elements in the array.
    numpy.max(): Finds the maximum value of the elements in the array.

In [26]:

# mean along axis 0
l = np.mean(a, axis=0)
print("Mean along axis 0:\n", l)

# mean along axis 1
m = np.mean(a, axis=1)
print("Mean along axis 1:\n", m)

# Calculate the median of the array
median = np.median(my_array)
print("The median of the array is:", median)



# Calculate the mean of the array
mean = np.mean(arr)
print("Mean:", mean)  # Output: Mean: 3.0

# Calculate the median of the array
median = np.median(arr)
print("Median:", median)  # Output: Median: 3.0

# Calculate the standard deviation of the array
std = np.std(arr)
print("Standard deviation:", std)  # Output: Standard deviation: 1.4142135623730951

# Calculate the variance of the array
var = np.var(arr)
print("Variance:", var)  # Output: Variance: 2.0

# Find the minimum value of the array
min_val = np.min(arr)
print("Minimum value:", min_val)  # Output: Minimum value: 1

# Find the maximum value of the array
max_val = np.max(arr)
print("Maximum value:", max_val)  # Output: Maximum value: 5

# Correlation coefficient
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[2, 4, 6], [1, 3, 5], [3, 6, 9]])
corr_coef = np.corrcoef(arr, arr2)
print("Correlation coefficient:\n", corr_coef)


Mean along axis 0:
 [4. 5. 6.]
Mean along axis 1:
 [2. 5. 8.]
The median of the array is: 3.0
Mean: 3.0
Median: 3.0
Standard deviation: 1.4142135623730951
Variance: 2.0
Minimum value: 1
Maximum value: 5
Correlation coefficient:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


# Pandas

## Dictionary


```
Create, Read, Update, Delete operations
```




In [27]:
ages = {'John': 32, 'Jane': 28, 'Bob': 45}

print(ages['John'])  # prints 32

ages['Alice'] = 20

del ages['Bob']

print(ages.keys())  # prints ['John', 'Jane', 'Alice']
print(ages.values())  # prints [32, 28, 20]
print(ages.items())  # prints [('John', 32), ('Jane', 28), ('Alice', 20)]


32
dict_keys(['John', 'Jane', 'Alice'])
dict_values([32, 28, 20])
dict_items([('John', 32), ('Jane', 28), ('Alice', 20)])


### 2d dictionary

```
.update() method
add sub-dictionary
key in dict
```


In [28]:
import pprint

# Dictionary of dictionaries
europe = { 'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } }


# Print out the capital of France
print(europe['france']['capital'])  # OUTPUT: paris


# key in dict: Returns True if the specified key is in the dictionary, False otherwise.
print('italy' in europe)  # OUTPUT: False

# Create sub-dictionary data
data = {'capital':'rome', 'population': 59.83}

# Add data to europe under key 'italy'
europe.update({'italy': data})

# Print europe
pprint.pprint(europe)

paris
False
{'france': {'capital': 'paris', 'population': 66.03},
 'germany': {'capital': 'berlin', 'population': 80.62},
 'italy': {'capital': 'rome', 'population': 59.83},
 'norway': {'capital': 'oslo', 'population': 5.084},
 'spain': {'capital': 'madrid', 'population': 46.77}}


In [29]:
# creating / converting a dictionary to a dataframe
import pandas as pd
europe_df = pd.DataFrame(europe)
europe_df

spain france germany norway  italy
capital     madrid  paris  berlin   oslo   rome
population   46.77  66.03   80.62  5.084  59.83

In [30]:
# Create the years and durations lists
years = list(range(2011, 2021))
durations = [103, 101, 99, 100, 100, 95, 95, 96, 93, 90]

# Create a dictionary with the two lists
movie_dict = {"years": years, "durations": durations}

# Print the dictionary
movie_dict

{'years': [2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020],
 'durations': [103, 101, 99, 100, 100, 95, 95, 96, 93, 90]}

In [31]:
# Convert CSV (comma-separated values) text file to a DataFrame
# europe_df = pd.read_csv('cars.csv', index_col=0)


In [32]:
# Update row labels using .index()
row_labels = ['city', 'people']

europe_df.index = row_labels

europe_df

spain france germany norway  italy
city    madrid  paris  berlin   oslo   rome
people   46.77  66.03   80.62  5.084  59.83

In [33]:
# Print out country column as Pandas Series
print("Pandas Series:\n", europe_df['spain'], "\n")

# Print out country column as Pandas DataFrame
print("Pandas DataFrame:\n", europe_df[['spain']], "\n")



Pandas Series:
 city      madrid
people     46.77
Name: spain, dtype: object 

Pandas DataFrame:
          spain
city    madrid
people   46.77 



## select cells in a Pandas DataFrame

There are several ways to select cells in a Pandas DataFrame:

1. Using **square bracket notation**: you can **select one or more columns** by passing a string or a list of strings containing the column name(s), and you can also filter rows based on conditions using boolean indexing.
   Example:

   - `df['column_name']` # one bracket for selecting a single column.
   - `df[['column_name_1', 'column_name_2']]` # two brackets for selecting multiple columns.


2. Using boolean indexing: you can **filter/subset rows** based on one or more conditions using logical operators (e.g., `&` for "and", `|` for "or", `~` for "not").
   Example:
      - `df[df['column_name'] > 10]` # select rows with a condition.

   - `df[(df['column_name_1'] > 10) & (df['column_name_2'] == 'string')]`


3. the `.isin()` method allows you to subsetting data based on a categorical variable to select rows from multiple categories by writing one condition instead of three separate ones.

  `dogs[dogs["color_column"].isin(["brown", "black", "tan"]]`




4. Using the `.loc[]` accessor: you can **select rows and columns** based on labels (i.e., row and column names).
   Example:
   - `df.loc[row_label, column_label]` # returns a single cell
   - `df.loc[row_label, :]` # returns a row as a series
   - `df.loc[:, 'column_label']` # returns column as Series
   - `df.loc[:, ['column_label']]` # returns column as DataFrame
   - `df.loc[row_label_1:row_label_2, column_label_1:column_label_2]` # returns the selected portion as a series
   - `df.loc[['row_label_1', 'row_label_2'], ['column_label_1', 'column_label_2']]` # returns sub-DataFrame
   - `df.loc[:, ['column_label_1', 'column_label_2']]` # returns 2 colums as DataFrame






5. Using the `.iloc[]` accessor: you can **select rows and columns** based on integer indices (i.e., row and column positions).
   Example:
   - `df.iloc[row_index, column_index]`
   - `df.iloc[:, column_index]`
   - `df.iloc[row_index, :]`
   - `df.iloc[row_index_1:row_index_2, column_index_1:column_index_2]`

6. Using the `.at[]` accessor: you can select a scalar value based on a specific row and column label.
   Example:
   - `df.at[row_label, column_label]`

7. Using the `.iat[]` accessor: you can select a scalar value based on specific row and column integer indices.
   Example:
   - `df.iat[row_index, column_index]`



Note that these methods can also be used to select rows or columns only, or to assign values to specific cells or slices of the DataFrame.

Adding new columns

`df['new_column'] = df['column_1'] + df['column_2']`

In [34]:
# add new row to dataframe using .loc

europe_df.loc["phone"] = [34, 33, 49, 47, 39]
europe_df

spain france germany norway  italy
city    madrid  paris  berlin   oslo   rome
people   46.77  66.03   80.62  5.084  59.83
phone       34     33      49     47     39

In [35]:
# Add a new column to the DataFrame using .loc

europe_df.loc[:, 'austria'] = ['vienna', 8.95, 43]
europe_df

spain france germany norway  italy austria
city    madrid  paris  berlin   oslo   rome  vienna
people   46.77  66.03   80.62  5.084  59.83    8.95
phone       34     33      49     47     39      43

In [36]:

# Select multiple DataFrame columns using brackets
print(europe_df[['spain', 'germany']])

print('\n')

print(europe_df['spain'])

         spain germany
city    madrid  berlin
people   46.77   80.62
phone       34      49


city      madrid
people     46.77
phone         34
Name: spain, dtype: object


In [37]:
# Selecting rows directly using slicing indecies
europe_df[1:3]

spain france germany norway  italy austria
people  46.77  66.03   80.62  5.084  59.83    8.95
phone      34     33      49     47     39      43

In [38]:
# Select multiple DataFrame rows by .loc labels
print(europe_df.loc[['city', 'phone']])

print('\n')

print(europe_df.loc['people'])

        spain france germany norway italy austria
city   madrid  paris  berlin   oslo  rome  vienna
phone      34     33      49     47    39      43


spain      46.77
france     66.03
germany    80.62
norway     5.084
italy      59.83
austria     8.95
Name: people, dtype: object


In [39]:
# select a signle cell by loc labels
europe_df.loc['city', 'france']

'paris'

In [40]:
# select entire dataframe rows by iloc index
print(europe_df.iloc[[0, 2]])

        spain france germany norway italy austria
city   madrid  paris  berlin   oslo  rome  vienna
phone      34     33      49     47    39      43


In [41]:
europe_df

spain france germany norway  italy austria
city    madrid  paris  berlin   oslo   rome  vienna
people   46.77  66.03   80.62  5.084  59.83    8.95
phone       34     33      49     47     39      43

In [42]:
cars = pd.read_csv('https://assets.datacamp.com/production/repositories/287/datasets/79b3c22c47a2f45a800c62cae39035ff2ea4e609/cars.csv', index_col = 0)
cars

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [43]:
# Selecting cells that match the condition and returns bolean value accordingly
dr = cars['cars_per_cap'] > 300
dr

US      True
AUS     True
JAP     True
IN     False
RU     False
MOR    False
EG     False
Name: cars_per_cap, dtype: bool

In [44]:
# Select the True rows only
sel = cars[dr]
sel

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False

In [45]:
# Do the previous example as a one-liner
sel = cars[cars['cars_per_cap'] > 300]
sel

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False

In [46]:
cpc = cars['cars_per_cap']
between = np.logical_and(cpc > 100, cpc < 500)
medium = cars[between]
medium

cars_per_cap country  drives_right
RU           200  Russia          True

In [47]:
medium = cars[np.logical_and(cars['cars_per_cap'] > 100, cars['cars_per_cap'] < 500)]
medium

cars_per_cap country  drives_right
RU           200  Russia          True

## Data Manipulation with pandas

#### Inspecting a DataFrame

When you get a new DataFrame to work with, the first thing you need to do is explore it and see what it contains. There are several useful methods and attributes for this.

    .head() returns the first few rows (the “head” of the DataFrame).
    .info() shows information on each of the columns, such as the data type and number of missing values.
    .shape returns the number of rows and columns of the DataFrame.
    .describe() calculates a few summary statistics for each column.


In [48]:
# Print the head of the homelessness data
print(cars.head(), '\n')

# Print information about homelessness
print(cars.info())

# Print the shape of homelessness
print('\n', cars.shape)

# Print a description of homelessness
print('\n', cars.describe())

     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True 

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, US to EG
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   cars_per_cap  7 non-null      int64 
 1   country       7 non-null      object
 2   drives_right  7 non-null      bool  
dtypes: bool(1), int64(1), object(1)
memory usage: 475.0+ bytes
None

 (7, 3)

        cars_per_cap
count      7.000000
mean     351.571429
std      345.595552
min       18.000000
25%       57.500000
50%      200.000000
75%      659.500000
max      809.000000


#### Parts of a DataFrame

To better understand DataFrame objects, it's useful to know that they consist of three components, stored as attributes:

    .values: A two-dimensional NumPy array of values.
    .columns: An index of columns: the column names.
    .index: An index for the rows: either row numbers or row names.


In [49]:
# Print the values of homelessness
print(cars.values, '\n')

# Print the column index of homelessness
print(cars.columns, '\n')

# Print the row index of homelessness
print(cars.index, '\n')

[[809 'United States' True]
 [731 'Australia' False]
 [588 'Japan' False]
 [18 'India' False]
 [200 'Russia' True]
 [70 'Morocco' True]
 [45 'Egypt' True]] 

Index(['cars_per_cap', 'country', 'drives_right'], dtype='object') 

Index(['US', 'AUS', 'JAP', 'IN', 'RU', 'MOR', 'EG'], dtype='object') 



#### Sorting rows

In cases where rows have the same value (this is common if you sort on a categorical variable), you may wish to break the ties by sorting on another column. You can sort on multiple columns in this way by passing a list of column names.

```
one column 	      df.sort_values("breed", ascending=False)
multiple columns 	df.sort_values(["breed", "weight_kg"], ascedning=[False, True])

```





In [50]:
# one column
cars.sort_values("cars_per_cap", ascending=False)

# multiple columns
cars.sort_values(["cars_per_cap", "country"], ascending=[False, True])

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True
IN             18          India         False

## Summary Statistics

In [51]:
# import pandas as pd
# index_col = 0 specify the first column as the index.
sales = pd.read_csv('/content/drive/MyDrive/AI/test_data/sales_subset.csv', index_col = 0)
sales

store type  department        date  weekly_sales  is_holiday  \
0          1    A           1  2010-02-05      24924.50       False   
1          1    A           1  2010-03-05      21827.90       False   
2          1    A           1  2010-04-02      57258.43       False   
3          1    A           1  2010-05-07      17413.94       False   
4          1    A           1  2010-06-04      17558.09       False   
...      ...  ...         ...         ...           ...         ...   
10769     39    A          99  2011-12-09        895.00       False   
10770     39    A          99  2012-02-03        350.00       False   
10771     39    A          99  2012-06-08        450.00       False   
10772     39    A          99  2012-07-13          0.06       False   
10773     39    A          99  2012-10-05        915.00       False   

       temperature_c  fuel_price_usd_per_l  unemployment  
0           5.727778              0.679451         8.106  
1           8.055556              0.693452         8.106  
2          16.816667              0.718284         7.808  
3          22.527778              0.748928         7.808  
4          27.050000              0.714586         7.808  
...              ...                   ...           ...  
10769       9.644444              0.834256         7.716  
10770      15.938889              0.887619         7.244  
10771      27.288889              0.911922         6.989  
10772      25.644444              0.860145         6.623  
10773      22.250000              0.955511         6.228  

[10774 rows x 9 columns]

Taking the minimum and maximum of a column of dates is handy for figuring out what time period your data covers.

In [52]:
# Print the maximum of the date column
print(sales['date'].max())

# Print the minimum of the date column
print(sales['date'].min())


2012-10-26
2010-02-05


Efficient summaries using .agg(function) : The aggregate, or agg, method allows you to compute custom summary statistics.

The custom function "IQR" in this case is short for inter-quartile ange, which is the 75th percentile minus the 25th percentile. It's an alternative to standard deviation that is helpful if your data contains outliers.

In [53]:
# df['column'].agg(function)
# A custom IQR function
def iqr(column):
    return column.quantile(0.75) - column.quantile(0.25)

# Print IQR of the temperature_c column
print(sales['temperature_c'].agg(iqr))

16.583333333333336


In [54]:
# Return summaries on multiple columns
print(sales[["temperature_c", 'fuel_price_usd_per_l', 'unemployment']].agg(iqr))

temperature_c           16.583333
fuel_price_usd_per_l     0.073176
unemployment             0.565000
dtype: float64


In [55]:
# Return a list of funcitons into .agg()
print(sales[["temperature_c", "fuel_price_usd_per_l", "unemployment"]].agg([iqr, np.median]))

        temperature_c  fuel_price_usd_per_l  unemployment
iqr         16.583333              0.073176         0.565
median      16.966667              0.743381         8.099


In [57]:
sales

store type  department        date  weekly_sales  is_holiday  \
0          1    A           1  2010-02-05      24924.50       False   
1          1    A           1  2010-03-05      21827.90       False   
2          1    A           1  2010-04-02      57258.43       False   
3          1    A           1  2010-05-07      17413.94       False   
4          1    A           1  2010-06-04      17558.09       False   
...      ...  ...         ...         ...           ...         ...   
10769     39    A          99  2011-12-09        895.00       False   
10770     39    A          99  2012-02-03        350.00       False   
10771     39    A          99  2012-06-08        450.00       False   
10772     39    A          99  2012-07-13          0.06       False   
10773     39    A          99  2012-10-05        915.00       False   

       temperature_c  fuel_price_usd_per_l  unemployment  
0           5.727778              0.679451         8.106  
1           8.055556              0.693452         8.106  
2          16.816667              0.718284         7.808  
3          22.527778              0.748928         7.808  
4          27.050000              0.714586         7.808  
...              ...                   ...           ...  
10769       9.644444              0.834256         7.716  
10770      15.938889              0.887619         7.244  
10771      27.288889              0.911922         6.989  
10772      25.644444              0.860145         6.623  
10773      22.250000              0.955511         6.228  

[10774 rows x 9 columns]

In [66]:
sales_1_1 = sales[(sales['store'] == 1) & (sales['department'] == 1)]
sales_1_1

store type  department        date  weekly_sales  is_holiday  \
0       1    A           1  2010-02-05      24924.50       False   
1       1    A           1  2010-03-05      21827.90       False   
2       1    A           1  2010-04-02      57258.43       False   
3       1    A           1  2010-05-07      17413.94       False   
4       1    A           1  2010-06-04      17558.09       False   
5       1    A           1  2010-07-02      16333.14       False   
6       1    A           1  2010-08-06      17508.41       False   
7       1    A           1  2010-09-03      16241.78       False   
8       1    A           1  2010-10-01      20094.19       False   
9       1    A           1  2010-11-05      34238.88       False   
10      1    A           1  2010-12-03      22517.56       False   
11      1    A           1  2011-01-07      15984.24       False   

    temperature_c  fuel_price_usd_per_l  unemployment  
0        5.727778              0.679451         8.106  
1        8.055556              0.693452         8.106  
2       16.816667              0.718284         7.808  
3       22.527778              0.748928         7.808  
4       27.050000              0.714586         7.808  
5       27.172222              0.705076         7.787  
6       30.644444              0.693980         7.787  
7       27.338889              0.680772         7.787  
8       22.161111              0.687640         7.838  
9       14.855556              0.710359         7.838  
10       9.594444              0.715378         7.838  
11       9.038889              0.786176         7.742

Cumulative statistics

In [67]:
# Sort sales_1_1 by date
sales_1_1 = sales_1_1.sort_values("date", ascending=True)

sales_1_1['cum_weekly_sales'] = sales['weekly_sales'].cumsum()

sales_1_1['cum_max_sales'] = sales['weekly_sales'].cummax()

print(sales_1_1[["date", "weekly_sales", "cum_weekly_sales", "cum_max_sales"]])

          date  weekly_sales  cum_weekly_sales  cum_max_sales
0   2010-02-05      24924.50          24924.50       24924.50
1   2010-03-05      21827.90          46752.40       24924.50
2   2010-04-02      57258.43         104010.83       57258.43
3   2010-05-07      17413.94         121424.77       57258.43
4   2010-06-04      17558.09         138982.86       57258.43
5   2010-07-02      16333.14         155316.00       57258.43
6   2010-08-06      17508.41         172824.41       57258.43
7   2010-09-03      16241.78         189066.19       57258.43
8   2010-10-01      20094.19         209160.38       57258.43
9   2010-11-05      34238.88         243399.26       57258.43
10  2010-12-03      22517.56         265916.82       57258.43
11  2011-01-07      15984.24         281901.06       57258.43
